### ISSUE TITLE
Get mask and gamma information from window

### ISSUE THREAD

**Issue by milibopp** [PistonDevelopers/gfx_window_shared#1]
Compared to the other output backends this one has a flaw that comes from lack of information obtainable from OpenGLWindow. Namely masks and gamma conversion are not determined from the window as in e.g. `gfx_window_glutin` but hard-coded to some default:

``` rust
SharedOutput {
    // ...
    mask: gfx::COLOR | gfx::DEPTH | gfx::STENCIL,
    supports_gamma_conversion: true,
}
```

The OpenGLWindow trait needs to be extended to make this work.

**Comment by bvssvni** [comment]
Closing because this library is deprecated. See https://github.com/PistonDevelopers/gfx_window_shared/issues/7
