### ISSUE TITLE
Deprecate this library

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_window_shared#7]
This library will be deprecated in 24 hours if there is no interest in developing it.

**Comment by kvark** [comment]
What is the recommended way now? piston_window?

**Comment by bvssvni** [comment]
@kvark piston_window is the most used. Do you want to use this library, or do you know anyone who uses it?

**Comment by kvark** [comment]
Nope

**Comment by bvssvni** [comment]
Done.
